# modules/analysis.py
# ─────────────────────────────────────────────────────
# ANALYSIS ENGINE — looks at ALL previous results and
# draws security conclusions.
#
# Four jobs:
#   1. WAF detection       → what firewall is in front?
#   2. Tech fingerprinting → what stack are they running?
#   3. Vulnerability hints → what might be exploitable?
#   4. Chain analyzer      → how do findings combine?
#
# This stage is mostly offline — it analyses data already
# collected. A few HTTP requests for WAF/tech detection.
# ─────────────────────────────────────────────────────

import re           # regex for pattern matching
import json         # parsing responses
import time         # small delays

import requests
requests.packages.urllib3.disable_warnings()


# ══════════════════════════════════════════════════════
#  WAF SIGNATURES
# ══════════════════════════════════════════════════════

# each WAF leaves fingerprints in response headers or body
# we check for these strings to identify the WAF
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "body":    ["cloudflare", "__cfduid", "cf-browser-verification"],
        "server":  ["cloudflare"],
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed"],
        "body":    ["akamaighost", "ak_bmsc"],
        "server":  ["akamaighost"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amzn-trace-id", "x-amz-cf-id"],
        "body":    ["aws-waf", "awswaf"],
        "server":  [],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "body":    ["incapsula", "visid_incap", "nlbi_", "_incap_ses"],
        "server":  ["incapsula"],
    },
    "F5 BIG-IP": {
        "headers": ["x-wa-info", "x-cnection"],
        "body":    ["bigipserver", "f5-trafficshield", "ts_uid"],
        "server":  ["big-ip", "f5"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body":    ["sucuri", "cloudproxy"],
        "server":  ["sucuri"],
    },
    "ModSecurity": {
        "headers": ["x-mod-security"],
        "body":    ["mod_security", "modsecurity", "not acceptable"],
        "server":  ["mod_security"],
    },
    "Barracuda": {
        "headers": ["barra_counter_session"],
        "body":    ["barracuda", "barra_counter"],
        "server":  [],
    },
    "Wordfence": {
        "headers": [],
        "body":    ["wordfence", "generated by wordfence"],
        "server":  [],
    },
    "Nginx WAF": {
        "headers": [],
        "body":    ["nginx", "openresty"],
        "server":  ["nginx", "openresty"],
    },
    "Fastly": {
        "headers": ["x-served-by", "x-cache", "x-cache-hits", "fastly-restarts"],
        "body":    ["fastly"],
        "server":  [],
    },
    "Vercel": {
        "headers": ["x-vercel-id", "x-vercel-cache"],
        "body":    [],
        "server":  [],
    },
    "Netlify": {
        "headers": ["x-nf-request-id"],
        "body":    [],
        "server":  ["netlify"],
    },
}

# headers we send to try to bypass WAF
# we pretend to be an internal/trusted IP
WAF_BYPASS_HEADERS = {
    "X-Forwarded-For":   "127.0.0.1",
    "X-Real-IP":         "127.0.0.1",
    "X-Originating-IP":  "127.0.0.1",
    "X-Remote-IP":       "127.0.0.1",
    "X-Client-IP":       "127.0.0.1",
    "True-Client-IP":    "127.0.0.1",
    "CF-Connecting-IP":  "127.0.0.1",
    "X-Host":            "localhost",
}


# ══════════════════════════════════════════════════════
#  TECH FINGERPRINT SIGNATURES
# ══════════════════════════════════════════════════════

# patterns for detecting technology stack
# checked against: headers, HTML body, cookies, URLs
TECH_SIGNATURES = {
    # ── CMS ───────────────────────────────────────────
    "WordPress": {
        "body":    ["/wp-content/", "/wp-includes/", "wp-json"],
        "headers": [],
        "cookies": ["wordpress_", "wp-settings"],
        "meta":    ["wordpress"],
    },
    "Drupal": {
        "body":    ["drupal", "/sites/default/files", "Drupal.settings"],
        "headers": ["x-drupal-cache", "x-generator"],
        "cookies": ["SESS"],
        "meta":    ["drupal"],
    },
    "Joomla": {
        "body":    ["/media/jui/", "joomla", "/components/com_"],
        "headers": [],
        "cookies": [],
        "meta":    ["joomla"],
    },
    "Magento": {
        "body":    ["mage/", "varien", "Magento"],
        "headers": ["x-magento-cache-debug"],
        "cookies": ["frontend"],
        "meta":    [],
    },
    "Shopify": {
        "body":    ["cdn.shopify.com", "Shopify.theme"],
        "headers": ["x-shopid", "x-shardid"],
        "cookies": ["_shopify_"],
        "meta":    [],
    },
    # ── frameworks ────────────────────────────────────
    "Laravel": {
        "body":    ["laravel", "csrf-token"],
        "headers": ["x-powered-by"],
        "cookies": ["laravel_session", "XSRF-TOKEN"],
        "meta":    [],
    },
    "Django": {
        "body":    ["csrfmiddlewaretoken", "django"],
        "headers": [],
        "cookies": ["csrftoken", "sessionid"],
        "meta":    [],
    },
    "Ruby on Rails": {
        "body":    ["csrf-param", "authenticity_token"],
        "headers": ["x-runtime", "x-powered-by"],
        "cookies": ["_session_id"],
        "meta":    [],
    },
    "ASP.NET": {
        "body":    ["__VIEWSTATE", "__EVENTVALIDATION", "asp.net"],
        "headers": ["x-aspnet-version", "x-aspnetmvc-version", "x-powered-by"],
        "cookies": ["ASP.NET_SessionId", "ASPXAUTH"],
        "meta":    [],
    },
    "Express / Node.js": {
        "body":    [],
        "headers": ["x-powered-by"],
        "cookies": ["connect.sid"],
        "meta":    [],
        "header_values": ["express", "node"],
    },
    "Next.js": {
        "body":    ["__NEXT_DATA__", "_next/static"],
        "headers": ["x-powered-by"],
        "cookies": [],
        "meta":    [],
        "header_values": ["next.js"],
    },
    "React": {
        "body":    ["react", "__react", "data-reactroot", "_reactRootContainer"],
        "headers": [],
        "cookies": [],
        "meta":    [],
    },
    "Vue.js": {
        "body":    ["vue", "__vue__", "data-v-"],
        "headers": [],
        "cookies": [],
        "meta":    [],
    },
    "Angular": {
        "body":    ["ng-version", "angular", "ng-app", "_nghost"],
        "headers": [],
        "cookies": [],
        "meta":    [],
    },
    # ── web servers ───────────────────────────────────
    "Nginx": {
        "body":    [],
        "headers": ["server"],
        "cookies": [],
        "meta":    [],
        "header_values": ["nginx"],
    },
    "Apache": {
        "body":    [],
        "headers": ["server"],
        "cookies": [],
        "meta":    [],
        "header_values": ["apache"],
    },
    "IIS": {
        "body":    [],
        "headers": ["server", "x-powered-by"],
        "cookies": [],
        "meta":    [],
        "header_values": ["microsoft-iis", "asp.net"],
    },
    "Caddy": {
        "body":    [],
        "headers": ["server"],
        "cookies": [],
        "meta":    [],
        "header_values": ["caddy"],
    },
    # ── cloud / hosting ───────────────────────────────
    "AWS S3": {
        "body":    ["amazonaws.com", "s3.amazonaws"],
        "headers": ["x-amz-request-id", "x-amz-id-2"],
        "cookies": [],
        "meta":    [],
    },
    "Cloudflare Pages": {
        "body":    [],
        "headers": ["cf-ray"],
        "cookies": [],
        "meta":    [],
    },
    "Google Cloud": {
        "body":    [],
        "headers": ["x-goog-generation", "x-guploader-uploadid"],
        "cookies": [],
        "meta":    [],
    },
    # ── analytics / tracking ──────────────────────────
    "Google Analytics": {
        "body":    ["google-analytics.com", "gtag", "UA-", "G-"],
        "headers": [],
        "cookies": ["_ga", "_gid", "_gat"],
        "meta":    [],
    },
    "Hotjar": {
        "body":    ["hotjar", "hjid"],
        "headers": [],
        "cookies": ["_hjid"],
        "meta":    [],
    },
}


# ══════════════════════════════════════════════════════
#  VULNERABILITY HINT RULES
# ══════════════════════════════════════════════════════

# each rule checks for a specific condition in the results
# and generates a hint if found
#
# structure:
# {
#   "id":       unique ID for the hint
#   "title":    short description
#   "severity": Critical / High / Medium / Low / Info
#   "detail":   explanation of the issue
#   "check":    lambda that takes (results) and returns True/False
# }

VULN_HINT_RULES = [

    # ── secrets ───────────────────────────────────────────────────────────
    {
        "id":       "JS-001",
        "title":    "AWS credentials found in JS files",
        "severity": "Critical",
        "detail":   (
            "AWS Access Key found in JavaScript. "
            "Attacker can use this to access AWS services, "
            "read S3 buckets, enumerate IAM users, and potentially "
            "pivot to full cloud account takeover."
        ),
        "check": lambda r: any(
            "AWS" in s.get("type", "")
            for s in r.get("js_secrets", [])
        ),
    },
    {
        "id":       "JS-002",
        "title":    "API keys / tokens exposed in JS files",
        "severity": "High",
        "detail":   (
            "API keys or tokens found in client-side JavaScript. "
            "These may allow unauthorized access to third-party services."
        ),
        "check": lambda r: len(r.get("js_secrets", [])) > 0,
    },

    # ── subdomain takeover ────────────────────────────────────────────────
    {
        "id":       "SUB-001",
        "title":    "Subdomain takeover vulnerability",
        "severity": "Critical",
        "detail":   (
            "One or more subdomains point to unclaimed external services. "
            "An attacker can register the service and take control of the "
            "subdomain — enabling phishing, cookie theft, and CSP bypass."
        ),
        "check": lambda r: len(r.get("takeovers", [])) > 0,
    },

    # ── open ports ────────────────────────────────────────────────────────
    {
        "id":       "PORT-001",
        "title":    "Docker API exposed on public port 2375",
        "severity": "Critical",
        "detail":   (
            "Docker API (port 2375) is open without TLS. "
            "This allows full container management, "
            "mounting host filesystem, and complete server takeover."
        ),
        "check": lambda r: any(
            p.get("port") == 2375
            for p in r.get("open_ports", [])
        ),
    },
    {
        "id":       "PORT-002",
        "title":    "Redis exposed without authentication",
        "severity": "Critical",
        "detail":   (
            "Redis (port 6379) is publicly accessible. "
            "Default Redis has no password. "
            "Attacker can read/write all data, "
            "or use SLAVEOF to pivot to RCE."
        ),
        "check": lambda r: any(
            p.get("port") == 6379
            for p in r.get("open_ports", [])
        ),
    },
    {
        "id":       "PORT-003",
        "title":    "MongoDB exposed without authentication",
        "severity": "Critical",
        "detail":   (
            "MongoDB (port 27017) is publicly accessible. "
            "Older MongoDB versions have no auth by default. "
            "Full database read/write access possible."
        ),
        "check": lambda r: any(
            p.get("port") == 27017
            for p in r.get("open_ports", [])
        ),
    },
    {
        "id":       "PORT-004",
        "title":    "Elasticsearch exposed without authentication",
        "severity": "Critical",
        "detail":   (
            "Elasticsearch (port 9200) is publicly accessible. "
            "Default Elasticsearch has no auth. "
            "Full index read/write/delete possible."
        ),
        "check": lambda r: any(
            p.get("port") == 9200
            for p in r.get("open_ports", [])
        ),
    },
    {
        "id":       "PORT-005",
        "title":    "Kubernetes API server exposed",
        "severity": "Critical",
        "detail":   (
            "Kubernetes API (port 6443) is publicly accessible. "
            "If misconfigured, attacker can enumerate pods, "
            "exec into containers, and access secrets."
        ),
        "check": lambda r: any(
            p.get("port") == 6443
            for p in r.get("open_ports", [])
        ),
    },
    {
        "id":       "PORT-006",
        "title":    "Telnet service detected",
        "severity": "High",
        "detail":   (
            "Telnet (port 23) transmits data in plaintext. "
            "Credentials are visible to anyone on the network path. "
            "Should be replaced with SSH."
        ),
        "check": lambda r: any(
            p.get("port") == 23
            for p in r.get("open_ports", [])
        ),
    },
    {
        "id":       "PORT-007",
        "title":    "RDP exposed on public internet",
        "severity": "High",
        "detail":   (
            "RDP (port 3389) is publicly accessible. "
            "Common target for brute-force and BlueKeep-style exploits. "
            "Should be behind VPN."
        ),
        "check": lambda r: any(
            p.get("port") == 3389
            for p in r.get("open_ports", [])
        ),
    },

    # ── missing security headers ──────────────────────────────────────────
    {
        "id":       "HDR-001",
        "title":    "Missing HSTS header",
        "severity": "Medium",
        "detail":   (
            "Strict-Transport-Security header not set. "
            "Browser may fall back to HTTP, "
            "enabling SSL stripping attacks."
        ),
        "check": lambda r: any(
            "Strict-Transport-Security" in svc.get("missing_headers", [])
            for svc in r.get("http_services", [])
        ),
    },
    {
        "id":       "HDR-002",
        "title":    "Missing Content-Security-Policy",
        "severity": "Medium",
        "detail":   (
            "No CSP header found. "
            "Makes XSS attacks more impactful — "
            "attacker can load any external scripts."
        ),
        "check": lambda r: any(
            "Content-Security-Policy" in svc.get("missing_headers", [])
            for svc in r.get("http_services", [])
        ),
    },
    {
        "id":       "HDR-003",
        "title":    "Clickjacking protection missing",
        "severity": "Low",
        "detail":   (
            "X-Frame-Options header not set. "
            "Page can be embedded in an iframe on a malicious site."
        ),
        "check": lambda r: any(
            "X-Frame-Options" in svc.get("missing_headers", [])
            for svc in r.get("http_services", [])
        ),
    },

    # ── tech stack specific ───────────────────────────────────────────────
    {
        "id":       "TECH-001",
        "title":    "WordPress installation detected",
        "severity": "Info",
        "detail":   (
            "WordPress detected. Check for: "
            "outdated plugins/themes, xmlrpc.php enabled, "
            "user enumeration via /?author=1, "
            "and wp-login.php brute-force."
        ),
        "check": lambda r: "WordPress" in r.get("tech_stack", []),
    },
    {
        "id":       "TECH-002",
        "title":    "ASP.NET ViewState detected",
        "severity": "Info",
        "detail":   (
            "ASP.NET __VIEWSTATE found. "
            "If ViewState MAC validation is disabled, "
            "this can lead to deserialization RCE."
        ),
        "check": lambda r: "ASP.NET" in r.get("tech_stack", []),
    },

    # ── DNS / WHOIS ───────────────────────────────────────────────────────
    {
        "id":       "DNS-001",
        "title":    "Domain expires within 90 days",
        "severity": "Medium",
        "detail":   (
            "Domain expiry date is within 90 days. "
            "If not renewed, attacker could register it "
            "and intercept email/traffic."
        ),
        "check": lambda r: _check_expiry(r),
    },
    {
        "id":       "DNS-002",
        "title":    "No SPF record found",
        "severity": "Medium",
        "detail":   (
            "No SPF TXT record in DNS. "
            "Anyone can send email spoofing this domain. "
            "Enables phishing attacks."
        ),
        "check": lambda r: not any(
            "SPF" in item.get("service", "")
            for item in r.get("dns_records", {}).get("interesting_txt", [])
        ),
    },
    {
        "id":       "DNS-003",
        "title":    "No DMARC record found",
        "severity": "Medium",
        "detail":   (
            "No DMARC TXT record found. "
            "Without DMARC, email spoofing is trivial. "
            "Combine with missing SPF for full email impersonation."
        ),
        "check": lambda r: not any(
            "DMARC" in item.get("service", "")
            for item in r.get("dns_records", {}).get("interesting_txt", [])
        ),
    },

    # ── admin panels ──────────────────────────────────────────────────────
    {
        "id":       "ADM-001",
        "title":    "Admin panel exposed publicly",
        "severity": "High",
        "detail":   (
            "An admin panel or management interface was found "
            "accessible without IP restriction. "
            "Target for brute-force and credential stuffing."
        ),
        "check": lambda r: any(
            svc.get("is_admin")
            for svc in r.get("http_services", [])
        ),
    },

    # ── shodan vulns ──────────────────────────────────────────────────────
    {
        "id":       "CVE-001",
        "title":    "Known CVEs found via Shodan",
        "severity": "Critical",
        "detail":   (
            "Shodan has identified known CVEs for this IP. "
            "Manual verification and patching required immediately."
        ),
        "check": lambda r: len(r.get("shodan_vulns", [])) > 0,
    },
]


def _check_expiry(results):
    """
    Helper for DNS-001 rule.
    Checks if domain expires within 90 days.
    """
    from datetime import datetime

    expiry = results.get("whois", {}).get("expires")
    if not expiry:
        return False

    try:
        exp_date = datetime.strptime(expiry, "%Y-%m-%d")
        days_left = (exp_date - datetime.now()).days
        return 0 < days_left < 90
    except Exception:
        return False


# ══════════════════════════════════════════════════════
#  SECTION 1 — WAF DETECTION
# ══════════════════════════════════════════════════════

def run_waf_detection(base_url, config):
    """
    Sends requests to the target and checks response
    headers + body for WAF fingerprints.

    Also sends a deliberately malicious payload to trigger
    WAF block page — WAFs often reveal themselves when blocking.

    Returns:
    - detected WAFs (list)
    - bypass headers to use in subsequent requests
    """

    detected = []

    # ── normal request fingerprinting ─────────────────────────────────────
    try:
        r = requests.get(
            base_url,
            timeout=config.get("timeout", 8),
            verify=False,
            headers={"User-Agent": "Mozilla/5.0 Chrome/122.0.0.0 Safari/537.36"}
        )

        # build a single string to search through
        # includes all headers + first 2000 chars of body
        headers_str = " ".join([
            f"{k.lower()}: {v.lower()}"
            for k, v in r.headers.items()
        ])
        body_sample = r.text[:2000].lower()
        search_text = headers_str + " " + body_sample

        for waf_name, sigs in WAF_SIGNATURES.items():
            # check header signatures
            header_hit = any(
                sig in headers_str
                for sig in sigs["headers"]
            )

            # check body signatures
            body_hit = any(
                sig in body_sample
                for sig in sigs["body"]
            )

            # check server header specifically
            server_val = r.headers.get("Server", "").lower()
            server_hit = any(
                sig in server_val
                for sig in sigs.get("server", [])
            )

            if header_hit or body_hit or server_hit:
                if waf_name not in detected:
                    detected.append(waf_name)

    except Exception:
        pass

    # ── WAF trigger request ────────────────────────────────────────────────
    # send a request with a classic XSS payload
    # WAFs often block this and show their block page
    # which reveals them even if normal requests don't
    try:
        trigger_url = f"{base_url}/?id=1<script>alert(1)</script>&q=../etc/passwd"
        r2 = requests.get(
            trigger_url,
            timeout=config.get("timeout", 8),
            verify=False,
            headers={"User-Agent": "Mozilla/5.0 Chrome/122.0.0.0"},
            allow_redirects=False,
        )

        # 403/406/429/503 on a malicious URL = WAF blocking
        if r2.status_code in [403, 406, 429, 503]:
            block_body = r2.text[:1000].lower()
            for waf_name, sigs in WAF_SIGNATURES.items():
                if any(sig in block_body for sig in sigs["body"]):
                    if waf_name not in detected:
                        detected.append(waf_name)

    except Exception:
        pass

    # build bypass headers based on what WAF was detected
    bypass_headers = dict(WAF_BYPASS_HEADERS)  # always use IP spoofing
    if "Cloudflare" in detected:
        bypass_headers["CF-Connecting-IP"] = "127.0.0.1"
    if "Akamai" in detected:
        bypass_headers["True-Client-IP"] = "127.0.0.1"

    return {
        "waf":             detected,
        "waf_detected":    len(detected) > 0,
        "bypass_headers":  bypass_headers,
    }


# ══════════════════════════════════════════════════════
#  SECTION 2 — TECH FINGERPRINTING
# ══════════════════════════════════════════════════════

def run_tech_fingerprint(base_url, config):
    """
    Fetches the target and detects technology stack from:
    - Response headers
    - HTML body content
    - Cookie names
    - Meta tags
    - Script/link tag patterns

    Returns list of detected technologies.
    """

    detected = []

    try:
        r = requests.get(
            base_url,
            timeout=config.get("timeout", 8),
            verify=False,
            headers={"User-Agent": "Mozilla/5.0 Chrome/122.0.0.0 Safari/537.36"},
            allow_redirects=True,
        )

        body_lower    = r.text[:5000].lower()
        headers_lower = {
            k.lower(): v.lower()
            for k, v in r.headers.items()
        }
        # cookie names
        cookie_str = " ".join(r.cookies.keys()).lower()

        # meta generator tag — many CMS put their name here
        # e.g. <meta name="generator" content="WordPress 6.4">
        meta_gen = ""
        meta_match = re.search(
            r'<meta[^>]+name=["\']generator["\'][^>]+content=["\']([^"\']+)["\']',
            r.text, re.I
        )
        if meta_match:
            meta_gen = meta_match.group(1).lower()

        for tech_name, sigs in TECH_SIGNATURES.items():

            hit = False

            # check body
            if any(sig.lower() in body_lower for sig in sigs["body"]):
                hit = True

            # check header names
            if any(h.lower() in headers_lower for h in sigs["headers"]):
                # also check header values if specified
                if "header_values" in sigs:
                    for hv in sigs["header_values"]:
                        for hk, hval in headers_lower.items():
                            if hv in hval:
                                hit = True
                else:
                    hit = True

            # check cookies
            if any(c.lower() in cookie_str for c in sigs["cookies"]):
                hit = True

            # check meta generator
            if any(m.lower() in meta_gen for m in sigs["meta"]):
                hit = True

            if hit and tech_name not in detected:
                detected.append(tech_name)

    except Exception:
        pass

    return detected


# ══════════════════════════════════════════════════════
#  SECTION 3 — VULNERABILITY HINTS
# ══════════════════════════════════════════════════════

def run_vuln_hints(results):
    """
    Runs all vuln hint rules against the collected results.

    Each rule has a "check" function (lambda) that takes
    the full results dict and returns True/False.

    If True → the condition for that vulnerability is met
    → we add it to the hints list.

    These are HINTS not confirmed vulnerabilities.
    They tell the pentester "go look here manually."
    """

    hints = []

    for rule in VULN_HINT_RULES:
        try:
            # run the check lambda against all results
            triggered = rule["check"](results)

            if triggered:
                hints.append({
                    "id":       rule["id"],
                    "title":    rule["title"],
                    "severity": rule["severity"],
                    "detail":   rule["detail"],
                })

        except Exception:
            # if a rule crashes (missing key etc.) just skip it
            pass

    # sort by severity: Critical first
    severity_order = {
        "Critical": 0,
        "High":     1,
        "Medium":   2,
        "Low":      3,
        "Info":     4,
    }
    hints.sort(key=lambda x: severity_order.get(x["severity"], 5))

    return hints


# ══════════════════════════════════════════════════════
#  SECTION 4 — CHAIN ANALYZER
# ══════════════════════════════════════════════════════

def run_chain_analysis(results, hints):
    """
    Looks at ALL findings together and identifies
    attack chains — combinations of vulnerabilities
    that are more dangerous together than separately.

    Think of it like: finding two puzzle pieces that fit.

    Example chain:
    JS file has an API key  +  /api/v1/users endpoint found
    → attacker uses the key to authenticate to the API
    → dumps all user data
    → account takeover

    Returns list of chain descriptions.
    """

    chains = []

    # helper: check if a hint ID was triggered
    triggered_ids = {h["id"] for h in hints}

    def has(hint_id):
        return hint_id in triggered_ids

    def has_tech(tech):
        return tech in results.get("tech_stack", [])

    # ── chain 1: JS secrets + API endpoints = ATO ─────────────────────────
    if has("JS-002") and results.get("js_endpoints"):
        chains.append({
            "title":    "JS Secret + API Endpoint → Account Takeover",
            "severity": "Critical",
            "steps": [
                "1. Leaked API key/token found in JS file",
                "2. API endpoints discovered from JS analysis",
                "3. Use the key to authenticate against API",
                "4. Enumerate users, read private data, or escalate privileges",
            ],
            "components": ["JS Secrets", "API Endpoints"],
        })

    # ── chain 2: subdomain takeover + cookies ─────────────────────────────
    if has("SUB-001"):
        chains.append({
            "title":    "Subdomain Takeover → Session Hijack",
            "severity": "Critical",
            "steps": [
                "1. Subdomain points to unclaimed external service",
                "2. Register the external service (free on most platforms)",
                "3. Host malicious page on the subdomain",
                "4. If cookies are not scoped properly → steal session cookies",
                "5. Use stolen session to access victim account",
            ],
            "components": ["Subdomain Takeover", "Cookie Scope"],
        })

    # ── chain 3: no SPF + no DMARC = email spoofing ───────────────────────
    if has("DNS-002") and has("DNS-003"):
        chains.append({
            "title":    "Missing SPF + Missing DMARC → Email Spoofing",
            "severity": "High",
            "steps": [
                "1. No SPF record → any server can send as this domain",
                "2. No DMARC → receiving servers won't reject spoofed mail",
                "3. Send phishing email appearing to come from target domain",
                "4. Employees/customers receive convincing phishing email",
            ],
            "components": ["Missing SPF", "Missing DMARC"],
        })

    # ── chain 4: exposed DB + no auth ─────────────────────────────────────
    db_ports = [6379, 27017, 9200, 5984, 11211]
    open_db_ports = [
        p for p in results.get("open_ports", [])
        if p.get("port") in db_ports
    ]
    if open_db_ports:
        db_names = [SERVICE_NAMES_SHORT.get(p["port"], str(p["port"]))
                    for p in open_db_ports]
        chains.append({
            "title":    f"Exposed Database → Direct Data Access",
            "severity": "Critical",
            "steps": [
                f"1. Database port(s) open: {', '.join(db_names)}",
                "2. Connect directly with default/no credentials",
                "3. Read/exfiltrate entire database",
                "4. Look for user credentials → reuse on login portals",
            ],
            "components": ["Open Database Port", "No Authentication"],
        })

    # ── chain 5: WordPress + exposed admin ────────────────────────────────
    if has_tech("WordPress") and has("ADM-001"):
        chains.append({
            "title":    "WordPress + Exposed Admin → Full Site Takeover",
            "severity": "High",
            "steps": [
                "1. WordPress installation detected",
                "2. wp-admin panel accessible publicly",
                "3. Brute-force or credential stuff wp-login.php",
                "4. Install malicious plugin → RCE on the server",
            ],
            "components": ["WordPress", "Exposed Admin Panel"],
        })

    # ── chain 6: Docker API exposed ───────────────────────────────────────
    if has("PORT-001"):
        chains.append({
            "title":    "Exposed Docker API → Full Server Takeover",
            "severity": "Critical",
            "steps": [
                "1. Docker API on port 2375 with no TLS/auth",
                "2. List all containers: GET /containers/json",
                "3. Create new container mounting host filesystem at /host",
                "4. Write SSH key to /host/root/.ssh/authorized_keys",
                "5. SSH into the actual host as root",
            ],
            "components": ["Docker API", "No Authentication"],
        })

    # ── chain 7: Kubernetes exposed ───────────────────────────────────────
    if has("PORT-005"):
        chains.append({
            "title":    "Exposed Kubernetes API → Cluster Takeover",
            "severity": "Critical",
            "steps": [
                "1. Kubernetes API server (6443) publicly accessible",
                "2. Check for anonymous access: kubectl --insecure get pods",
                "3. Enumerate secrets: kubectl get secrets -A",
                "4. Exec into containers: kubectl exec -it pod -- /bin/bash",
                "5. Access cloud metadata for IAM credentials",
            ],
            "components": ["Kubernetes API", "Possible Anonymous Access"],
        })

    return chains


# short service names for chain descriptions
SERVICE_NAMES_SHORT = {
    6379:  "Redis",
    27017: "MongoDB",
    9200:  "Elasticsearch",
    5984:  "CouchDB",
    11211: "Memcached",
}


# ══════════════════════════════════════════════════════
#  MAIN FUNCTION — called by reconx.py
# ══════════════════════════════════════════════════════

def run_analysis(results, config):
    """
    Main entry point — reconx.py calls this as:
        run_analysis(results, config)

    Unlike other modules, this one receives the FULL
    results dict from all previous stages.

    It adds its own findings back into the same dict
    and returns the updated version.
    """

    analysis_results = {}

    # get base URL from validation results
    base_url = results.get("base_url", "")
    if not base_url:
        domain   = results.get("domain", "")
        base_url = f"https://{domain}" if domain else ""

    # ── 1. WAF detection ──────────────────────────────────────────────────
    if base_url:
        if config.get("verbose"):
            print("    running WAF detection...")

        waf_results = run_waf_detection(base_url, config)
        analysis_results["waf"]            = waf_results.get("waf", [])
        analysis_results["waf_detected"]   = waf_results.get("waf_detected", False)
        analysis_results["bypass_headers"] = waf_results.get("bypass_headers", {})

    # ── 2. tech fingerprinting ────────────────────────────────────────────
    if base_url:
        if config.get("verbose"):
            print("    running tech fingerprinting...")

        tech = run_tech_fingerprint(base_url, config)
        analysis_results["tech_stack"] = tech

        # merge into main results so vuln hints can see it
        results["tech_stack"] = tech

    # ── 3. vulnerability hints ────────────────────────────────────────────
    if config.get("verbose"):
        print("    running vulnerability hints...")

    # merge analysis results into main results
    # so hint rules can access everything
    results.update(analysis_results)

    hints = run_vuln_hints(results)
    analysis_results["vuln_hints"] = hints

    # count by severity for summary
    analysis_results["hint_summary"] = {
        "critical": sum(1 for h in hints if h["severity"] == "Critical"),
        "high":     sum(1 for h in hints if h["severity"] == "High"),
        "medium":   sum(1 for h in hints if h["severity"] == "Medium"),
        "low":      sum(1 for h in hints if h["severity"] == "Low"),
        "info":     sum(1 for h in hints if h["severity"] == "Info"),
        "total":    len(hints),
    }

    # ── 4. chain analysis ─────────────────────────────────────────────────
    if config.get("verbose"):
        print("    running chain analysis...")

    chains = run_chain_analysis(results, hints)
    analysis_results["chains"] = chains

    return analysis_results